[project]
[tool.poetry]
name = "growth-mindsetchallenge"
version = "0.1.0"
description = "Your project description"
authors = ["Mehwish Sheikh"]
readme = "README.md"
python = ">=3.10,<3.13"
dependencies = []
